---

http:
  host: "0.0.0.0"
  port: "8080"

refreshInterval: "1h"

repos:
  # gateway-28
  - name: gateway-28-7-noarch
    url: https://packages.konghq.com/public/gateway-28/rpm/el/7/noarch
  - name: gateway-28-7-x86_64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/7/x86_64
  - name: gateway-28-7-aarch64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/7/aarch64
  - name: gateway-28-8-noarch
    url: https://packages.konghq.com/public/gateway-28/rpm/el/8/noarch
  - name: gateway-28-8-x86_64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/8/x86_64
  - name: gateway-28-8-aarch64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/8/aarch64
  - name: gateway-28-9-noarch
    url: https://packages.konghq.com/public/gateway-28/rpm/el/9/noarch
  - name: gateway-28-9-x86_64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/9/x86_64
  - name: gateway-28-9-aarch64
    url: https://packages.konghq.com/public/gateway-28/rpm/el/9/aarch64
