name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v4

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --verbose ./cmd/yum2npm
        env:
          KO_DOCKER_REPO: ghcr.io/kong/yum2npm
